// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_order_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "checkout-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderStore is a mock of OrderStore interface.
type MockOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStoreMockRecorder
	isgomock struct{}
}

// MockOrderStoreMockRecorder is the mock recorder for MockOrderStore.
type MockOrderStoreMockRecorder struct {
	mock *MockOrderStore
}

// NewMockOrderStore creates a new mock instance.
func NewMockOrderStore(ctrl *gomock.Controller) *MockOrderStore {
	mock := &MockOrderStore{ctrl: ctrl}
	mock.recorder = &MockOrderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStore) EXPECT() *MockOrderStoreMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderStore) CreateOrder(ctx context.Context, userID int, items []domain.LineItem, total int, status string) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userID, items, total, status)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderStoreMockRecorder) CreateOrder(ctx, userID, items, total, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderStore)(nil).CreateOrder), ctx, userID, items, total, status)
}

// DecrementStock mocks base method.
func (m *MockOrderStore) DecrementStock(ctx context.Context, itemID, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementStock", ctx, itemID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementStock indicates an expected call of DecrementStock.
func (mr *MockOrderStoreMockRecorder) DecrementStock(ctx, itemID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementStock", reflect.TypeOf((*MockOrderStore)(nil).DecrementStock), ctx, itemID, quantity)
}

// GetOrderByID mocks base method.
func (m *MockOrderStore) GetOrderByID(ctx context.Context, id int) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderStoreMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderStore)(nil).GetOrderByID), ctx, id)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderStore) GetOrdersByUserID(ctx context.Context, userID, limit, offset int, cursor string) ([]*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID, limit, offset, cursor)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderStoreMockRecorder) GetOrdersByUserID(ctx, userID, limit, offset, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderStore)(nil).GetOrdersByUserID), ctx, userID, limit, offset, cursor)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderStore) UpdateOrderStatus(ctx context.Context, id int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderStoreMockRecorder) UpdateOrderStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderStore)(nil).UpdateOrderStatus), ctx, id, status)
}

// MockbalanceService is a mock of balanceService interface.
type MockbalanceService struct {
	ctrl     *gomock.Controller
	recorder *MockbalanceServiceMockRecorder
	isgomock struct{}
}

// MockbalanceServiceMockRecorder is the mock recorder for MockbalanceService.
type MockbalanceServiceMockRecorder struct {
	mock *MockbalanceService
}

// NewMockbalanceService creates a new mock instance.
func NewMockbalanceService(ctrl *gomock.Controller) *MockbalanceService {
	mock := &MockbalanceService{ctrl: ctrl}
	mock.recorder = &MockbalanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbalanceService) EXPECT() *MockbalanceServiceMockRecorder {
	return m.recorder
}

// DebitForPurchase mocks base method.
func (m *MockbalanceService) DebitForPurchase(ctx context.Context, userID int, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebitForPurchase", ctx, userID, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DebitForPurchase indicates an expected call of DebitForPurchase.
func (mr *MockbalanceServiceMockRecorder) DebitForPurchase(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitForPurchase", reflect.TypeOf((*MockbalanceService)(nil).DebitForPurchase), ctx, userID, amount)
}

// GetBalance mocks base method.
func (m *MockbalanceService) GetBalance(ctx context.Context, userID int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockbalanceServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockbalanceService)(nil).GetBalance), ctx, userID)
}
