// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_cart_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "checkout-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCartStore is a mock of CartStore interface.
type MockCartStore struct {
	ctrl     *gomock.Controller
	recorder *MockCartStoreMockRecorder
	isgomock struct{}
}

// MockCartStoreMockRecorder is the mock recorder for MockCartStore.
type MockCartStoreMockRecorder struct {
	mock *MockCartStore
}

// NewMockCartStore creates a new mock instance.
func NewMockCartStore(ctrl *gomock.Controller) *MockCartStore {
	mock := &MockCartStore{ctrl: ctrl}
	mock.recorder = &MockCartStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartStore) EXPECT() *MockCartStoreMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockCartStore) AddToCart(ctx context.Context, userID int, item domain.LineItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", ctx, userID, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockCartStoreMockRecorder) AddToCart(ctx, userID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockCartStore)(nil).AddToCart), ctx, userID, item)
}

// CreateUserCart mocks base method.
func (m *MockCartStore) CreateUserCart(ctx context.Context, cart *domain.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserCart", ctx, cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserCart indicates an expected call of CreateUserCart.
func (mr *MockCartStoreMockRecorder) CreateUserCart(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserCart", reflect.TypeOf((*MockCartStore)(nil).CreateUserCart), ctx, cart)
}

// DeleteUserCart mocks base method.
func (m *MockCartStore) DeleteUserCart(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserCart indicates an expected call of DeleteUserCart.
func (mr *MockCartStoreMockRecorder) DeleteUserCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserCart", reflect.TypeOf((*MockCartStore)(nil).DeleteUserCart), ctx, userID)
}

// GetUserCart mocks base method.
func (m *MockCartStore) GetUserCart(ctx context.Context, userID int) (*domain.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCart", ctx, userID)
	ret0, _ := ret[0].(*domain.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCart indicates an expected call of GetUserCart.
func (mr *MockCartStoreMockRecorder) GetUserCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCart", reflect.TypeOf((*MockCartStore)(nil).GetUserCart), ctx, userID)
}

// RemoveCartItem mocks base method.
func (m *MockCartStore) RemoveCartItem(ctx context.Context, userID, itemID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCartItem", ctx, userID, itemID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCartItem indicates an expected call of RemoveCartItem.
func (mr *MockCartStoreMockRecorder) RemoveCartItem(ctx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCartItem", reflect.TypeOf((*MockCartStore)(nil).RemoveCartItem), ctx, userID, itemID)
}

// UpdateCartItem mocks base method.
func (m *MockCartStore) UpdateCartItem(ctx context.Context, userID, itemID, quantity int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, userID, itemID, quantity)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockCartStoreMockRecorder) UpdateCartItem(ctx, userID, itemID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockCartStore)(nil).UpdateCartItem), ctx, userID, itemID, quantity)
}
